# Generated by Django 4.2.7 on 2024-03-09 05:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit', '0003_easyhabit_goodhabit_fee_some_goodhabit_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('action', models.CharField(max_length=200)),
                ('fee_some', models.CharField(blank=True, max_length=200, null=True, verbose_name='награда предметом')),
                ('it_easy_habit', models.BooleanField(default=False)),
                ('it_public', models.BooleanField(default=True)),
                ('period', models.CharField(choices=[('week', 'Раз в неделю'), ('every_day', 'Каждый день')], default='every_day', max_length=20, verbose_name='периодичность')),
                ('time_action', models.PositiveIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120)])),
                ('other_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='habit.habit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='goodhabit',
            name='fee_habit',
        ),
        migrations.RemoveField(
            model_name='goodhabit',
            name='user',
        ),
        migrations.DeleteModel(
            name='EasyHabit',
        ),
        migrations.DeleteModel(
            name='GoodHabit',
        ),
    ]
